"use client";

export default function TermsConditionsPage() {
  return (
    <main className="bg-white mt-20">
      <section className="py-16">
        <div className="max-w-7xl mx-auto px-4">
          {/* TITLE */}
          <div className="mb-10">
            <h1 className="text-4xl font-bold mb-4">
              SignSpark AI Terms of Service
            </h1>
            <p className="text-gray-500 text-lg">
              Version 1.0 • Effective Date: May 15, 2026 • Last Updated: Feb 11,
              2026
            </p>
          </div>

          <div className="space-y-8 text-lg text-gray-700">
            {/* Section 1 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                1. Acceptance of Terms
              </h2>
              <p className="mb-4">
                By accessing or using the SignSpark AI platform ("Service"),
                accessible via our website or mobile application, you agree to
                be bound by these Terms of Service ("Terms"). If you disagree
                with any part of these terms, you may not access the Service.
              </p>
              <div className="bg-amber-50 border border-amber-200 p-4 rounded-lg">
                <p className="text-amber-800">
                  <strong>
                    "Beta" Notice (Applicable May 15, 2026 – June 15, 2026):
                  </strong>{" "}
                  During the Beta phase, the Service is provided "AS IS" and "AS
                  AVAILABLE" for testing purposes. We make no warranties
                  regarding uptime, accuracy, or data preservation. We reserve
                  the right to wipe data or reset accounts during this period.
                </p>
              </div>
            </div>

            {/* Section 2 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                2. Nature of Our Service (Important Disclaimers)
              </h2>
              <p className="mb-4">
                SignSpark AI is an <strong>informational analysis tool</strong>{" "}
                designed to assist consumers in understanding automotive
                contracts. By using this Service, you acknowledge and agree to
                the following:
              </p>
              <ul className="list-disc ml-6 space-y-4">
                <li>
                  <strong>We Are Not Lawyers:</strong> SignSpark AI is not a law
                  firm and does not provide legal advice. The "Contract Audits,"
                  "Risk Flags," and negotiation scripts are generated by
                  artificial intelligence based on common patterns. They are for
                  educational purposes only and are not a substitute for the
                  advice of an attorney.
                </li>
                <li>
                  <strong>We Are Not Financial Advisors:</strong> The "Fairness
                  Score" and financial analysis provided are estimates based on
                  market data. We do not guarantee loan approval, specific
                  interest rates, or financial savings.
                </li>
                <li>
                  <strong>You Make the Final Decision:</strong> You are solely
                  responsible for verifying all terms, numbers, and clauses with
                  the dealership before signing any binding agreement. SignSpark
                  AI is not a party to your vehicle purchase or lease agreement.
                </li>
              </ul>
            </div>

            {/* Section 3 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                3. User Accounts and Responsibilities
              </h2>
              <ul className="list-disc ml-6 space-y-4">
                <li>
                  <strong>Account Security:</strong> You are responsible for
                  safeguarding your login credentials. You must notify us
                  immediately of any unauthorized use of your account.
                </li>
                <li>
                  <strong>Accuracy of Input:</strong> The accuracy of our
                  analysis depends on the clarity of the documents you upload.
                  You agree to review the data extracted by our AI (e.g.,
                  vehicle price, APR) and correct any errors before relying on
                  the report.
                </li>
                <li>
                  <strong>Prohibited Use:</strong> You may not use the Service
                  to:
                  <ul className="list-disc ml-8 mt-2 space-y-1">
                    <li>Analyze contracts for fraudulent purposes.</li>
                    <li>
                      Upload documents containing illegal content or malware.
                    </li>
                    <li>
                      Reverse engineer or attempt to copy our AI algorithms.
                    </li>
                  </ul>
                </li>
              </ul>
            </div>

            {/* Section 4 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                4. Payment and Subscriptions
              </h2>
              <ul className="list-disc ml-6 space-y-4">
                <li>
                  <strong>Free Tier:</strong> We may offer limited access to
                  features (e.g., basic scanning) at no cost.
                </li>
                <li>
                  <strong>Pro Services:</strong> Access to detailed "Fairness
                  Reports," "Hidden Fee Detection," and advanced negotiation
                  tools requires a payment (e.g., one-time fee or subscription).
                </li>
                <li>
                  <strong>Billing:</strong> By selecting a paid service (e.g.,
                  the $89.99 Pro Upgrade), you authorize us to charge your
                  designated payment method.
                </li>
                <li>
                  <strong>Refunds:</strong> Due to the digital nature of our
                  reports, all sales are final once the "Fairness Report" or
                  analysis has been revealed to you, unless otherwise required
                  by law.
                </li>
              </ul>
            </div>

            {/* Section 5 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                5. Intellectual Property
              </h2>
              <ul className="list-disc ml-6 space-y-4">
                <li>
                  <strong>Your Data:</strong> You retain all ownership rights to
                  the documents and personal data you upload ("User Content").
                </li>
                <li>
                  <strong>Our Platform:</strong> SignSpark AI retains all
                  rights, title, and interest in the Service, including our
                  proprietary AI models, code, fairness algorithms, and the
                  "SignSpark" brand.
                </li>
              </ul>
            </div>

            {/* Section 6 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                6. Privacy and Data Security
              </h2>
              <p>
                Your use of the Service is also governed by our{" "}
                <strong>Privacy Policy</strong>, which explains how we collect,
                safeguard, and disclose information that results from your use
                of the Service.
              </p>
            </div>

            {/* Section 7 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                7. Limitation of Liability
              </h2>
              <p className="mb-4">
                <strong>READ THIS CAREFULLY:</strong> To the maximum extent
                permitted by law, SignSpark AI shall not be liable for any
                indirect, incidental, special, consequential, or punitive
                damages, including without limitation:
              </p>
              <ul className="list-disc ml-6 space-y-3 mb-4">
                <li>
                  Financial losses incurred from a bad vehicle purchase or lease
                  deal.
                </li>
                <li>
                  Errors in contract analysis (e.g., the AI failing to detect a
                  specific fee).
                </li>
                <li>Loss of data or service interruptions.</li>
              </ul>
              <p>
                In no event shall our total liability to you exceed the amount
                you paid us for the Service (e.g., $89.99) or $100, whichever is
                greater.
              </p>
            </div>

            {/* Section 8 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                8. Indemnification
              </h2>
              <p>
                You agree to indemnify and hold harmless SignSpark AI, its
                employees, and partners from any claims, damages, or expenses
                arising out of your use of the Service or your violation of
                these Terms.
              </p>
            </div>

            {/* Section 9 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">
                9. Changes to Terms
              </h2>
              <p>
                We reserve the right to modify these Terms at any time. If a
                revision is material, we will try to provide at least 30 days'
                notice prior to any new terms taking effect. Your continued use
                of the Service after those revisions constitutes your agreement
                to the new terms.
              </p>
            </div>

            {/* Section 10 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">10. Governing Law</h2>
              <p>
                These Terms shall be governed by the laws of the State of New
                Jersey, without regard to its conflict of law provisions.
              </p>
            </div>

            {/* Section 11 */}
            <div>
              <h2 className="text-2xl font-semibold mb-4">11. Contact Us</h2>
              <p className="mb-3">
                If you have any questions about these Terms, please contact us
                at:
              </p>
              <p className="font-medium">Email: legal@signspark.com</p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
