"use client";
import Image from "next/image";
import Link from "next/link";

export default function BlogDetailPage() {
  return (
    <main className="bg-white">
      {/* HERO IMAGE */}
      <section className="pt-20">
        <div className="relative h-[30vh] sm:h-[65vh] w-full">
          <Image
            src="/assets/img/blog/blog2.png"
            alt="blog image"
            fill
            className="object-fill"
          />
        </div>
      </section>

      {/* BLOG CONTENT */}
      <section className="py-16">
        <div className="max-w-7xl mx-auto px-4">
          {/* TITLE */}
          <div className="mb-8">
            <h1 className="text-4xl font-bold mb-4">
              Stop Asking, Start Negotiating: How AI Scripts Saved One Buyer
              $2,400
            </h1>

            <div className="flex justify-between flex-wrap gap-4 items-center">
              <span className="text-green-700 bg-green-100 px-5 py-1 rounded-full text-lg">
                By SignSpark Editorial Team
              </span>

              <p className="text-gray-500 text-lg">7 Minutes Read Time</p>
            </div>
          </div>

          {/* INTRO */}
          <div className="space-y-4 text-lg text-gray-700">
            <p>"Can you do any better on the price?"</p>

            <p>
              If you have ever asked a car dealer that question, you’ve already
              lost.
            </p>

            <p>
              When you ask a vague question, you get a vague answer:
              <em>
                {" "}
                "We're already losing money on this car," or "That's just the
                standard fee everyone pays."
              </em>
              The conversation ends there. You sign, feeling like you left money
              on the table.
            </p>

            <p>
              This is exactly where Michael, a graphic designer from Austin,
              found himself last month.
            </p>

            <p>
              This is exactly where Michael, a graphic designer from Austin,
              found himself last month. He was staring at a contract for a new
              SUV that was
              <strong> $3,000 over his budget.</strong>
            </p>

            <p>
              But unlike most buyers, Michael didn't ask "if they could do
              better." He looked at his phone, read a script generated by
              SignSpark, and saved
              <strong> $2,400 in less than five minutes.</strong>
            </p>

            <p>Here is exactly how he did it.</p>
          </div>

          {/* SECTION */}
          <div className="mt-14">
            <h2 className="text-3xl font-semibold mb-6">
              The Setup: The "Standard" Rip-Off
            </h2>

            <p className="text-lg text-gray-700 mb-4">
              Michael had negotiated a sale price of $34,000 for a Toyota RAV4.
              But when he sat down in the finance office, the contract in front
              of him listed a "Total Cash Price" of **$37,200**.
            </p>

            <p className="text-lg text-gray-700 mb-6">
              Where did the extra $3,200 come from? The Finance Manager pointed
              to three lines:
            </p>

            <ul className="list-disc ml-6 space-y-2 text-lg text-gray-700">
              <li>
                <strong>"P.D.I. Fee"</strong> ($995)
              </li>

              <li>
                <strong>"Paint & Fabric Defense"</strong> ($895)
              </li>

              <li>
                <strong>"Market Adjustment"</strong> ($1,310)
              </li>
            </ul>

            <p className="text-lg text-gray-700 mt-6">
              "They told me these were mandatory," Michael said. "The manager
              said P.D.I. stands for Pre-Delivery Inspection and every dealer
              charges it."
            </p>
          </div>

          {/* TURNING POINT */}
          <div className="mt-14">
            <h2 className="text-3xl font-semibold mb-6">
              The Turning Point: Data vs. Opinion
            </h2>

            <p className="text-lg text-gray-700 mb-4">
              In the past, Michael would have argued, been told "no," and likely
              given up. This time, he opened the SignSpark App and snapped a
              photo of the contract.
            </p>

            <p className="text-lg text-gray-700 mb-4">
              The AI didn't just flag the fees; it explained what they actually
              were.
            </p>

            <ul className="list-disc ml-6 space-y-3 text-lg text-gray-700">
              <li>
                <strong>"P.D.I. Fee"</strong> Flagged as unfair. (The
                manufacturer pays the dealer to inspect the car. Charging the
                customer is double-dipping).
              </li>

              <li>
                <strong>Paint Defense</strong> Flagged as overpriced. (A $20
                spray wax marked up 4,000%).
              </li>
            </ul>

            <p className="text-lg text-gray-700 mt-6">
              Then he tapped <strong>"How do I remove this?"</strong>
            </p>

            <p className="text-lg text-gray-700 mt-4">
              The app generated a specific script based on the leverage Michael
              had (he was ready to buy today).
            </p>
          </div>

          {/* SCRIPT SECTION */}
          <div className="mt-14">
            <h2 className="text-3xl font-semibold mb-6">
              The Script: "Say This, Not That"
            </h2>

            <p className="text-lg text-gray-700 mb-6">
              Here is the exact difference between what Michael wanted to say,
              and what SignSpark told him to say.
            </p>

            <h3 className="text-xl font-semibold mb-4">
              ❌ The Amateur Approach (What fails)
            </h3>

            <ul className="list-disc ml-6 space-y-3 text-lg text-gray-700">
              <li>
                <strong>Buyer:</strong> "These fees seem really high. Can you
                take them off? I really don't want to pay for paint protection."
              </li>

              <li>
                <strong>Dealer:</strong> "I understand, but the protection is
                already applied to the car. We can't scrape it off. And the
                inspection fee is corporate policy; I can't change it."
              </li>

              <li>
                <strong>Result: $0 Saved.</strong>
              </li>
            </ul>

            <h3 className="text-xl font-semibold mt-10 mb-4">
              ✅ The SignSpark Approach (What worked)
            </h3>

            <ul className="list-disc ml-6 space-y-3 text-lg text-gray-700">
              <li>
                <strong>Michael (Reading App Script): </strong> "I noticed
                you've listed a $995 P.D.I. fee. According to the manufacturer
                spec sheet, Pre-Delivery Inspection is reimbursed to the dealer
                by the factory. Asking me to pay this is double-charging."
              </li>

              <li>
                <strong>Michael (Continuing): </strong> "Regarding the Paint
                Defense—I did not request this add-on. Please remove the charge,
                or I will proceed to [Competitor Name] who has a similar unit in
                stock without these markups. I am ready to sign right now at the
                agreed price of $34,000 plus tax."
              </li>
            </ul>
          </div>

          {/* OUTCOME */}
          <div className="mt-14">
            <h2 className="text-3xl font-semibold mb-6">The Outcome</h2>

            <p className="text-lg text-gray-700 mb-4">
              The Finance Manager paused. The "corporate policy" excuse
              vanished.
            </p>

            <p className="text-lg text-gray-700 mb-4">
              Why? Because Michael wasn't asking for a favor—he was calling out
              a discrepancy using facts.
            </p>

            <ul className="list-disc ml-6 space-y-3 text-lg text-gray-700">
              <li>
                <strong>The Result:</strong> The manager removed the $995 P.D.I.
                fee and the $1,310 Market Adjustment immediately. He reduced the
                Paint Protection to $100 (cost).
              </li>

              <li>
                <strong>Total Savings: </strong> $2,400..
              </li>

              <li>
                <strong>Time Taken:</strong> 4 minutes.
              </li>

              <li>
                <strong>Cost of SignSpark Pro:</strong> $19.99
              </li>
            </ul>
          </div>

          {/* FINAL */}
          <div className="mt-14">
            <h2 className="text-3xl font-semibold mb-6">
              Why "Scripts" Are Your Superpower
            </h2>

            <p className="text-lg text-gray-700 mb-4">
              Dealers are trained professionals. They negotiate 50 times a
              month. You negotiate once every five years. They have scripts to
              overcome your objections.
            </p>

            <p className="text-lg text-gray-700 mb-4">
              SignSpark Pro gives you your own scripts.
            </p>

            <p className="text-lg text-gray-700 mb-4">
              It levels the playing field by turning "begging" into "business."
              You don't need to be aggressive, rude, or loud. You just need to
              be accurate.
            </p>

            <p className="text-lg font-semibold mb-6">
              Don't leave thousands on the table because you didn't know what to
              say.
            </p>

            <a href="#!" className="text-purple-600 font-semibold text-lg">
              {">"} Upgrade to SignSpark Pro and Get Your Custom Negotiation
              Script
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}
